

from PyQt4 import QtCore, QtGui
from Connections import *
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object,  Connections):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(673, 188)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 241, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 171, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 25, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(130, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setProperty("value", 4.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(0, 16, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(130, 15, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_7.setFont(font)
        self.doubleSpinBox_7.setProperty("value", 0.5)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(380, 0, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 91, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.spinBox_3 = QtGui.QSpinBox(self.frame_3)
        self.spinBox_3.setGeometry(QtCore.QRect(90, 10, 51, 16))
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 81, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBox = QtGui.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(0, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 36, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 55, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_10 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_10.setGeometry(QtCore.QRect(0, 85, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_12 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_12.setGeometry(QtCore.QRect(0, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_13 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_13.setGeometry(QtCore.QRect(0, 100, 97, 22))
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(240, 120, 231, 21))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushButton = QtGui.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 111, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 0, 111, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 50, 241, 31))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 141, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(0, 16, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.spinBox_7 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_7.setGeometry(QtCore.QRect(160, 11, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setMaximum(99)
        self.spinBox_7.setProperty("value", 99)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.label_19 = QtGui.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(200, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(470, 120, 201, 21))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 0, 151, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(240, 0, 141, 121))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalSlider = QtGui.QSlider(self.frame_6)
        self.horizontalSlider.setGeometry(QtCore.QRect(-1, 50, 141, 20))
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setProperty("value", 8)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_5 = QtGui.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 121, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_3 = QtGui.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalSlider_2 = QtGui.QSlider(self.frame_6)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(0, 90, 141, 20))
        self.horizontalSlider_2.setMaximum(10)
        self.horizontalSlider_2.setProperty("value", 3)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(520, 0, 151, 121))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_2 = QtGui.QLabel(self.frame_7)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBox_6 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.spinBox_2 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_2.setGeometry(QtCore.QRect(100, 12, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.checkBox_5 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 29, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.label_8 = QtGui.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(0, 15, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.checkBox_7 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_7.setGeometry(QtCore.QRect(0, 60, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_8 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_8.setGeometry(QtCore.QRect(0, 75, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_9 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_9.setGeometry(QtCore.QRect(0, 89, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_11 = QtGui.QCheckBox(self.frame_7)
        self.checkBox_11.setGeometry(QtCore.QRect(0, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.frame_8 = QtGui.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(0, 80, 241, 61))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_9 = QtGui.QLabel(self.frame_8)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 101, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalSlider_3 = QtGui.QSlider(self.frame_8)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(70, 20, 161, 21))
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setMaximum(8)
        self.horizontalSlider_3.setProperty("value", 2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.label_12 = QtGui.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(0, 20, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame_8)
        self.label_13.setGeometry(QtCore.QRect(60, 40, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(210, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.connect()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PartyMeter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Thresholds :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Minimum Face certanity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "New person difference level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Main Camera ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Front camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Show main view", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Validate face", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Mark detected faces", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("MainWindow", "Flip image verticaly", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("MainWindow", "Run face analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("MainWindow", "Print results", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Turn on camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Turn off camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Remembering faces:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Don\'t remove from memory last :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "persons", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Results :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Run data analysis module", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Time makes difference", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Time importance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Finding new person:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "X Position importance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Rare camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "Show rare view", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Run reverse camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Reverse camera ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", "Validate face", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow", "Mark detected objects", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("MainWindow", "Run face analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("MainWindow", "Flip image verticaly", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Analysis precision: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Cascade scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "High", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Low", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

